const TEXTURE_EMPTY_ATLAS = 0;
const TEXTURE_EMPTY_ATLAS_MIPMAP = 1;
const TEXTURE_WORLD_ATLAS = 2;
const TEXTURE_WORLD_ATLAS_MIPMAP = 3;
const TEXTURE_SYMBOL_ATLAS = 4;
const TEXTURE_SYMBOL_ATLAS_MIPMAP = 5;
const TEXTURE_SYMBOL_BRIGHT_ATLAS = 6;
const TEXTURE_SYMBOL_BRIGHT_ATLAS_MIPMAP = 7;
const TEXTURE_EMPTY_MATERIAL = 8;
const TEXTURE_EMPTY_MATERIAL_MIPMAP = 9;
const TEXTURE_SKYBOX_ATLAS = 10;
const TEXTURE_SKYBOX_ATLAS_MIPMAP = 11;
const TEXTURE_TERRAIN_MATERIAL = 12;
const TEXTURE_TERRAIN_MATERIAL_MIPMAP = 13;
const TEXTURE_DRAGON_BODY_MATERIAL = 14;
const TEXTURE_DRAGON_BODY_MATERIAL_MIPMAP = 15;

type MaterialTextureId =
  | typeof TEXTURE_EMPTY_MATERIAL
  | typeof TEXTURE_TERRAIN_MATERIAL
  | typeof TEXTURE_DRAGON_BODY_MATERIAL
  | typeof TEXTURE_DRAGON_BODY_MATERIAL_MIPMAP
  ;

type AtlusTextureId = 
  | typeof TEXTURE_EMPTY_ATLAS
  | typeof TEXTURE_EMPTY_ATLAS_MIPMAP
  | typeof TEXTURE_WORLD_ATLAS
  | typeof TEXTURE_WORLD_ATLAS_MIPMAP
  | typeof TEXTURE_SYMBOL_ATLAS
  | typeof TEXTURE_SYMBOL_ATLAS_MIPMAP
  | typeof TEXTURE_SYMBOL_BRIGHT_ATLAS
  | typeof TEXTURE_SYMBOL_BRIGHT_ATLAS_MIPMAP
  ;