const TEXTURE_EMPTY = 0;
const TEXTURE_EMPTY_MIPMAP = 1;
const TEXTURE_MAP = 2;
const TEXTURE_MAP_MIPMAP = 3;
const TEXTURE_SKYBOX = 4;
const TEXTURE_SKYBOX_MIPMAP = 5;
const TEXTURE_GRASS = 6;
const TEXTURE_GRASS_MIPMAP = 7;
