const TEXTURE_EMPTY_MAP = 0;
const TEXTURE_EMPTY_MAP_MIPMAP = 1;
const TEXTURE_WORLD_MAP = 2;
const TEXTURE_WORLD_MAP_MIPMAP = 3;
const TEXTURE_SYMBOL_MAP = 4;
const TEXTURE_SYMBOL_MAP_MIPMAP = 5;
const TEXTURE_EMPTY_ARRAY = 6;
const TEXTURE_EMPTY_ARRAY_MIPMAP = 7;
const TEXTURE_SKYBOX = 8;
const TEXTURE_SKYBOX_MIPMAP = 9;
const TEXTURE_TERRAIN = 10;
const TEXTURE_TERRAIN_MIPMAP = 11;

type MaterialTextureId =
  | typeof TEXTURE_EMPTY_ARRAY
  | typeof TEXTURE_SKYBOX
  | typeof TEXTURE_TERRAIN
  ;

type AtlusTextureId = 
  | typeof TEXTURE_EMPTY_MAP
  | typeof TEXTURE_EMPTY_MAP_MIPMAP
  | typeof TEXTURE_WORLD_MAP
  | typeof TEXTURE_WORLD_MAP_MIPMAP
  | typeof TEXTURE_SYMBOL_MAP
  | typeof TEXTURE_SYMBOL_MAP_MIPMAP
  ;